language: objective-c
osx_image: xcode7.3
xcode_project: StreamingMusicPlayer.xcodeproj

env:
  global:
  #- WORKSPACE=
  - PROJECT=StreamingMusicPlayer.xcodeproj
  - FRAMEWORK_SCHEME=StreamingMusicPlayer
  - SDK=iphonesimulator9.3
  - DESTINATION_PLATFORM='platform=iOS Simulator,name=iPhone 6,OS=9.3'

before_install:
  - SIMULATOR_ID=$(xcrun instruments -s | grep -o "iPhone 6s (9.3) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")

before_script:
- carthage version
- carthage checkout

#build RxSwift
- (cd ./Carthage/Checkouts/RxSwift && set -o pipefail && xcodebuild -scheme "RxSwift-iOS" -workspace "Rx.xcworkspace" -sdk "$SDK" -configuration Release SYMROOT=../../../Build  | xcpretty -c)
- (cd ./Carthage/Checkouts/RxSwift && set -o pipefail && xcodebuild -scheme "RxCocoa-iOS" -workspace "Rx.xcworkspace" -sdk "$SDK" -configuration Release SYMROOT=../../../Build  | xcpretty -c)
- (cd ./Carthage/Checkouts/RxSwift && set -o pipefail && xcodebuild -scheme "RxTests-iOS" -workspace "Rx.xcworkspace" -sdk "$SDK" -configuration Release SYMROOT=../../../Build  | xcpretty -c)
- (cd ./Carthage/Checkouts/RxSwift && set -o pipefail && xcodebuild -scheme "RxBlocking-iOS" -workspace "Rx.xcworkspace" -sdk "$SDK" -configuration Release SYMROOT=../../../Build  | xcpretty -c)

#copy RxSwift frameworks to Carthage/Build folder
- cp -R -f ./Build/Release-iphonesimulator/ ./Carthage/Build/iOS

#build other frameworks
- carthage update realm-cocoa --platform iOS
- carthage update RxHttpClient --platform iOS --configuration Debug
- carthage update RxHttpClientJasonExtension --platform iOS
- carthage update RxStreamPlayer --platform iOS
- carthage update OHHTTPStubs --platform iOS
- carthage update JASON --platform iOS

script:
- open -a "simulator" --args -CurrentDeviceUDID $SIMULATOR_ID
#- set -o pipefail && xcodebuild -scheme "$FRAMEWORK_SCHEME" -project "$PROJECT" -sdk "$SDK" -configuration Debug ONLY_ACTIVE_ARCH=YES -destination "$DESTINATION_PLATFORM" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES clean build  | xcpretty -c
- set -o pipefail && xcodebuild -scheme "$FRAMEWORK_SCHEME" -project "$PROJECT" -sdk "$SDK" -configuration Debug ONLY_ACTIVE_ARCH=YES -destination "$DESTINATION_PLATFORM" -enableCodeCoverage YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES clean test  | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash) -J '^StreamingMusicPlayer$'
