// Generated by Apple Swift version 2.2 (swiftlang-703.0.18.1 clang-703.0.29)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import AVFoundation;
@import ObjectiveC;
@import Foundation;
@import RealmSwift;
@import Foundation.NSURLSession;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"

@interface AVAsset (SWIFT_EXTENSION(RxStreamPlayer))
@end


@interface AVAssetResourceLoader (SWIFT_EXTENSION(RxStreamPlayer))
@end


SWIFT_CLASS("_TtC14RxStreamPlayer35AVAssetResourceLoaderEventsObserver")
@interface AVAssetResourceLoaderEventsObserver : NSObject
@property (nonatomic) BOOL shouldWaitForLoading;
- (nonnull instancetype)initWithShouldWaitForLoading:(BOOL)shouldWaitForLoading OBJC_DESIGNATED_INITIALIZER;
@end

@class AVAssetResourceLoadingRequest;

@interface AVAssetResourceLoaderEventsObserver (SWIFT_EXTENSION(RxStreamPlayer)) <AVAssetResourceLoaderDelegate>
- (BOOL)resourceLoader:(AVAssetResourceLoader * _Nonnull)resourceLoader shouldWaitForLoadingOfRequestedResource:(AVAssetResourceLoadingRequest * _Nonnull)loadingRequest;
- (void)resourceLoader:(AVAssetResourceLoader * _Nonnull)resourceLoader didCancelLoadingRequest:(AVAssetResourceLoadingRequest * _Nonnull)loadingRequest;
@end


@interface AVAssetResourceLoaderEventsObserver (SWIFT_EXTENSION(RxStreamPlayer))
@end


@interface AVAssetResourceLoadingContentInformationRequest (SWIFT_EXTENSION(RxStreamPlayer))
@end


@interface AVAssetResourceLoadingDataRequest (SWIFT_EXTENSION(RxStreamPlayer))
@end


@interface AVAssetResourceLoadingRequest (SWIFT_EXTENSION(RxStreamPlayer))
@end


@interface AVPlayer (SWIFT_EXTENSION(RxStreamPlayer))
- (void)setPlayerRate:(float)rate;
@end


@interface AVPlayerItem (SWIFT_EXTENSION(RxStreamPlayer))
@end


@interface AVURLAsset (SWIFT_EXTENSION(RxStreamPlayer))
@end


@interface NSFileManager (SWIFT_EXTENSION(RxStreamPlayer))
@end


@interface NSMutableOrderedSet (SWIFT_EXTENSION(RxStreamPlayer))
@end


@interface NSString (SWIFT_EXTENSION(RxStreamPlayer))
@property (nonatomic, readonly, copy) NSString * _Nonnull streamResourceUid;
@end


@interface NSURL (SWIFT_EXTENSION(RxStreamPlayer))
- (BOOL)fileExists;
- (void)deleteFile;
@end


@interface NSUserDefaults (SWIFT_EXTENSION(RxStreamPlayer))
- (void)saveData:(id _Nonnull)object forKey:(NSString * _Nonnull)forKey;
- (id _Nullable)loadRawData:(NSString * _Nonnull)forKey;
@end

@class NSData;
@class RLMRealm;
@class RLMObjectSchema;
@class RLMSchema;

SWIFT_CLASS("_TtC14RxStreamPlayer10RealmAlbum")
@interface RealmAlbum : RealmSwiftObject
@property (nonatomic, readonly, copy) NSString * _Nonnull uid;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, strong) NSData * _Nullable artwork;
- (nonnull instancetype)initWithUid:(NSString * _Nonnull)uid name:(NSString * _Nonnull)name OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (NSString * _Nullable)primaryKey;
@end


@interface RealmAlbum (SWIFT_EXTENSION(RxStreamPlayer))
@end


SWIFT_CLASS("_TtC14RxStreamPlayer11RealmArtist")
@interface RealmArtist : RealmSwiftObject
@property (nonatomic, readonly, copy) NSString * _Nonnull uid;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
- (nonnull instancetype)initWithUid:(NSString * _Nonnull)uid name:(NSString * _Nonnull)name OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (NSString * _Nullable)primaryKey;
@end


@interface RealmArtist (SWIFT_EXTENSION(RxStreamPlayer))
@end


SWIFT_CLASS("_TtC14RxStreamPlayer13RealmPlayList")
@interface RealmPlayList : RealmSwiftObject
@property (nonatomic, readonly, copy) NSString * _Nonnull uid;
@property (nonatomic, copy) NSString * _Nonnull name;
- (nonnull instancetype)initWithUid:(NSString * _Nonnull)uid name:(NSString * _Nonnull)name OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (NSString * _Nullable)primaryKey;
@end


@interface RealmPlayList (SWIFT_EXTENSION(RxStreamPlayer))
@end


SWIFT_CLASS("_TtC14RxStreamPlayer20RealmPlayerQueueItem")
@interface RealmPlayerQueueItem : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uid;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
+ (NSString * _Nullable)primaryKey;
@end


SWIFT_CLASS("_TtC14RxStreamPlayer16RealmPlayerState")
@interface RealmPlayerState : RealmSwiftObject
@property (nonatomic, readonly) BOOL shuffle;
@property (nonatomic, readonly) BOOL repeatQueue;
@property (nonatomic, strong) RealmPlayerQueueItem * _Nullable currentItem;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14RxStreamPlayer10RealmTrack")
@interface RealmTrack : RealmSwiftObject
@property (nonatomic, readonly, copy) NSString * _Nonnull uid;
@property (nonatomic, readonly, copy) NSString * _Nonnull title;
@property (nonatomic, readonly) float duration;
@property (nonatomic, readonly, strong) RealmAlbum * _Nullable albumInternal;
- (nonnull instancetype)initWithUid:(NSString * _Nonnull)uid title:(NSString * _Nonnull)title duration:(float)duration OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (NSString * _Nullable)primaryKey;
@end


@interface RealmTrack (SWIFT_EXTENSION(RxStreamPlayer))
@end

@class NSMutableURLRequest;

SWIFT_CLASS("_TtC14RxStreamPlayer14StreamDataTask")
@interface StreamDataTask : NSObject
- (nonnull instancetype)initWithRequest:(NSMutableURLRequest * _Nonnull)request OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithUrl:(NSURL * _Nonnull)url headers:(NSDictionary<NSString *, NSString *> * _Nullable)headers;
- (void)resume;
@end

@class NSURLSession;
@class NSURLSessionDataTask;
@class NSURLResponse;
@class NSURLSessionTask;
@class NSError;

@interface StreamDataTask (SWIFT_EXTENSION(RxStreamPlayer)) <NSURLSessionDataDelegate, NSURLSessionDelegate, NSURLSessionTaskDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask didReceiveResponse:(NSURLResponse * _Nonnull)response completionHandler:(void (^ _Nonnull)(NSURLSessionResponseDisposition))completionHandler;
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask didReceiveData:(NSData * _Nonnull)data;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didCompleteWithError:(NSError * _Nullable)error;
@end


@interface UIApplication (SWIFT_EXTENSION(RxStreamPlayer))
@end


@interface _SwiftNativeNSString (SWIFT_EXTENSION(RxStreamPlayer))
@property (nonatomic, readonly, copy) NSString * _Nonnull streamResourceUid;
@end

#pragma clang diagnostic pop
